# Generated by Django 4.2.3 on 2023-07-18 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("release", models.DateField()),
                ("genre", models.CharField(max_length=50)),
                ("nation", models.CharField(max_length=50)),
                ("showtime", models.TimeField()),
                ("rating", models.DecimalField(decimal_places=1, max_digits=2)),
                ("director", models.CharField(max_length=100)),
                ("actor", models.CharField(max_length=200)),
                ("grade", models.CharField(max_length=10)),
                ("imgfile", models.ImageField(blank=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="movies.movie",
                    ),
                ),
            ],
        ),
    ]
