# Generated by Django 4.2.3 on 2023-07-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="imgfile",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
